spring:
  application:
    name: GetHealthy
  datasource:
    url: jdbc:postgresql://localhost:5432/get_healthy
    username: get_healthy
    password: get_healthy
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
      enabled: true
      change-log: classpath:db/changelog.xml